apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
   
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 30m
      receiver: webhook-telegram
      
      routes:
      - match:
          severity: critical
        receiver: webhook-telegram
      - match: 
          severity: warning
        receiver: webhook-telegram

    receivers:
    - name: webhook-telegram
      webhook_configs:
        - send_resolved: false
          url: 'http://prometheus-bot:9087/alert/<Your Telegram Chat ID>'